### PR TITLE
Feedback

### PR DESCRIPTION
**Pull request by Carkappa**
Implemented feedback under lib/pages/feedback.dart. 

There are few error such as not being able to drawer from home_page in feedback.dart.

### CODE REVIEW

**Comment by Carkappa** [comment]
These will be fix when I finish my exam 😄

**Comment by Daniel-J101** [comment]
Screenshot 2024-09-23 at 12 38 47 PM
it's a little hard to view changes in this PR because of some file structure changes that might've been done on accident. Let's call sometime to go over it, either after you get to work on the changes or before, whichever works better for you.
let's also plan to do some git/github desktop work in the call

**Comment by Daniel-J101** [comment]
did manage to look at the feedback widget, here are some references that might be helpful to look at when debugging the navigation issue
[What is MaterialApp?](https://api.flutter.dev/flutter/material/MaterialApp-class.html)
[Where should it go and how many should you have?](https://stackoverflow.com/questions/65880760/is-it-okay-to-have-two-material-apps-in-one-flutter)
[What does the current `main.dart` look like?](https://github.com/FRC-Strategy-App/FRC-Strategy-App/blob/Feedback/FRC-Strategy-App/lib/main.dart)

**Comment by Daniel-J101** [comment]
lets do wednesday, i got an exam wednesday morning 😄

**Comment by Carkappa** [comment]
Bet sounds good. Gl on ur exam

**Pull request closed without merging**
